export const AUTOMATION_PRESETS = [
  {
    id: "interview",
    name: "Interview",
    nameDe: "Interview",
    category: "Podcast",
    icon: "🎙️",
    description: "Gentle leveling & speech warmth. Perfect for podcasts & dialogues.",
    descriptionDe: "Sanfte Pegelanpassung & Sprachwärme. Perfekt für Podcasts & Dialoge.",
    activeBg: "bg-cyan-500/15 border-cyan-400 text-cyan-300 font-bold",
    settings: {
      fadeInDuration: 0.5,
      fadeOutDuration: 0.8,
      noiseGateThreshold: 12,
      isNormalized: true,
      compressorEnabled: true,
      compMidThreshold: -20,
      compMidRatio: 3.0,
      compMidMakeup: 4,
      compLowThreshold: -24,
      compLowRatio: 2.5,
      compLowMakeup: 2,
      compHighThreshold: -22,
      compHighRatio: 2.5,
      compHighMakeup: 1,
    }
  },
  {
    id: "dialogue",
    name: "Co-Host",
    nameDe: "Co-Moderator",
    category: "Podcast",
    icon: "👥",
    description: "Balanced dialogue levels & background noise suppression.",
    descriptionDe: "Ausgeglichene Dialog-Pegel & Hintergrundgeräusch-Unterdrückung.",
    activeBg: "bg-cyan-500/15 border-cyan-400 text-cyan-300 font-bold",
    settings: {
      fadeInDuration: 0.4,
      fadeOutDuration: 0.6,
      noiseGateThreshold: 15,
      isNormalized: true,
      compressorEnabled: true,
      compMidThreshold: -18,
      compMidRatio: 2.8,
      compMidMakeup: 3,
      compLowThreshold: -22,
      compLowRatio: 2.2,
      compLowMakeup: 1,
      compHighThreshold: -20,
      compHighRatio: 2.2,
      compHighMakeup: 1,
    }
  },
  {
    id: "hype",
    name: "Hype Intro",
    nameDe: "Hype-Intro",
    category: "Short-form Social",
    icon: "🔥",
    description: "Punchy, heavy compression with a dramatic fade tail for intense introductions.",
    descriptionDe: "Druckvolle, starke Kompression mit dramatischem Fade-Auslauf für intensive Intros.",
    activeBg: "bg-violet-500/15 border-violet-400 text-violet-300 font-bold",
    settings: {
      fadeInDuration: 0.2,
      fadeOutDuration: 1.5,
      noiseGateThreshold: 8,
      isNormalized: true,
      compressorEnabled: true,
      compMidThreshold: -12,
      compMidRatio: 6.0,
      compMidMakeup: 6,
      compLowThreshold: -18,
      compLowRatio: 4.0,
      compLowMakeup: 3,
      compHighThreshold: -15,
      compHighRatio: 4.0,
      compHighMakeup: 3,
    }
  },
  {
    id: "tiktok",
    name: "TikTok V.O.",
    nameDe: "TikTok V.O.",
    category: "Short-form Social",
    icon: "🎵",
    description: "Crisp highs and high presence tailored for mobile devices.",
    descriptionDe: "Klarer Hochtonbereich und hohe Präsenz optimiert für Mobilgeräte.",
    activeBg: "bg-violet-500/15 border-violet-400 text-violet-300 font-bold",
    settings: {
      fadeInDuration: 0.2,
      fadeOutDuration: 0.4,
      noiseGateThreshold: 10,
      isNormalized: true,
      compressorEnabled: true,
      compMidThreshold: -14,
      compMidRatio: 4.5,
      compMidMakeup: 5,
      compLowThreshold: -16,
      compLowRatio: 3.5,
      compLowMakeup: 2,
      compHighThreshold: -12,
      compHighRatio: 4.5,
      compHighMakeup: 4,
    }
  },
  {
    id: "command",
    name: "Voice Command",
    nameDe: "Sprachbefehl",
    category: "System Voice",
    icon: "⚡",
    description: "Ultra-fast curves & heavy noise gating to isolate crisp vocal instructions.",
    descriptionDe: "Ultraschnelle Kurven & starkes Noise Gate zur Isolierung klarer Sprachbefehle.",
    activeBg: "bg-amber-500/15 border-amber-400 text-amber-300 font-bold",
    settings: {
      fadeInDuration: 0.1,
      fadeOutDuration: 0.1,
      noiseGateThreshold: 24,
      isNormalized: true,
      compressorEnabled: true,
      compMidThreshold: -16,
      compMidRatio: 4.0,
      compMidMakeup: 2,
      compLowThreshold: -15,
      compLowRatio: 5.0,
      compLowMakeup: 0,
      compHighThreshold: -18,
      compHighRatio: 3.5,
      compHighMakeup: 1,
    }
  },
  {
    id: "tts",
    name: "TTS Reader",
    nameDe: "TTS-Reader",
    category: "System Voice",
    icon: "🤖",
    description: "Flat, highly transparent leveling for artificial speech readers.",
    descriptionDe: "Flache, hochtransparente Pegelanpassung für künstliche Sprachleser.",
    activeBg: "bg-amber-500/15 border-amber-400 text-amber-300 font-bold",
    settings: {
      fadeInDuration: 0.1,
      fadeOutDuration: 0.2,
      noiseGateThreshold: 6,
      isNormalized: true,
      compressorEnabled: true,
      compMidThreshold: -22,
      compMidRatio: 2.0,
      compMidMakeup: 1,
      compLowThreshold: -26,
      compLowRatio: 1.8,
      compLowMakeup: 0,
      compHighThreshold: -24,
      compHighRatio: 1.8,
      compHighMakeup: 0,
    }
  }
];
