apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: miasanai-external-secrets
  namespace: miasanai
spec:
  # Refresh keys from GCP Secret Manager every hour
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: miasanai-secrets
    creationPolicy: Owner
  data:
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: GEMINI_API_KEY
        version: "latest"
    - secretKey: FAL_API_KEY
      remoteRef:
        key: FAL_API_KEY
        version: "latest"
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: OPENAI_API_KEY
        version: "latest"
    - secretKey: LEONARDO_API_KEY
      remoteRef:
        key: LEONARDO_API_KEY
        version: "latest"
