apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: miasanai-python-keys
  namespace: miasanai
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: miasanai-python-keys-secret
    creationPolicy: Owner
  data:
    # Synchronisiert den gesamten Inhalt des Python-Secrets "Keys" in ein Kubernetes Secret
    - secretKey: keys.py
      remoteRef:
        key: Keys # Name des Secrets im GCP Secret Manager (projects/project-0f0650fd-50cf-4f08-86c/secrets/Keys)
        version: "latest"
