apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: miasanai
spec:
  provider:
    gcpsm:
      # Automatically resolves project ID using workload identity, or you can specify explicitly:
      projectID: "project-0f0650fd-50cf-4f08-86c"
      auth:
        secretRef:
          # Workload Identity handles ambient GCP token injection automatically.
          # No static Service Account keys needed in the cluster!
          secretAccessKeyRef: {}
